### ISSUE TITLE
Cannot open entities popup once anchor link used

### ISSUE THREAD

**Issue by deanfourie1** [ShadowAya/anchor-card#10]
So, basically when I click an anchor link and it takes me to the appropriate part of the dashboard, I cannot open any entity popups, they popup then instantly disappear.

They will only work again if I refresh my dashboard. 

Any ideas?

**Comment by ShadowAya** [comment]
Tested and you're right. I'll investigate today. The sections view is tough 🙁

**Comment by deanfourie1** [comment]
Yea thanks, so close now haha will be so nice when its working!

**Comment by ShadowAya** [comment]
The issue is actually the `backout` option. It does the same thing on lovelace. Something on the frontend changed so clicking stuff updates the URL, but with the same URL, thus starting the process of going back.

I also found that clicking something on lovelace does a replacestate (doesn't push new URL to history), while sections do a pushstate (adding a new URL to browser history).

This is bizarre. I'm gonna have to change up how lovelace does backouts, but for sections, the whole thing is now 90% simpler.

**Comment by ShadowAya** [comment]
Update: I found out `backout` is actually redundant. For any "navigate" action, you can set [navigation_replace](https://www.home-assistant.io/dashboards/actions/#navigation_replace) to true, via the code editor.

Before I ship the changes I'm gonna polish some code and then it should be up

**Comment by ShadowAya** [comment]
@deanfourie1 I just released [v4](https://github.com/ShadowAya/anchor-card/releases/tag/v4). It addresses the issue and adds config GUI.

Apologies if the changes to config get annoying, but my `backout` solution was bad (didn't know about the native solution)
The config screen will warn you when you used backout, pointing to a solution, and it'll get removed from your config automatically (to clean up)

Let me know if everything went smoothly!

**Comment by deanfourie1** [comment]
Thanks so much! All is working now. This is great!
